function old_state = DAC_find_oldstate_from_new(new_state,new_cutpoints,old_cutpoints) 
% This function is to find the corresponding old state of a VP node to a
% new state generated by more cutting points. 
% -wsun, Feb. 7, 2014.


if new_state > length(new_cutpoints)
    old_state = length(old_cutpoints) + 1 ;
    return ;
end

value = new_cutpoints(new_state) ;
for k=1:length(old_cutpoints)
    if value <= old_cutpoints(k)
        old_state = k ;
        return ;
    end    
end

old_state = length(old_cutpoints) + 1  ;